language: java
jdk:
- oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  slack:
    secure: ceFDoYAYk+5QTuo+ydI8KT47ZQnrZfRMYlLHx7Wb0auwP+5G0fcoMPm+INsLW4JHrQc2C5E+Ch6tyuPxT+jCUjOtmrhA4KE2d+ZZVdR8raaqeBshvUiVuEhrRR+9wPqwE8/YP/17N5jC3xl3d4bPYcTmLtvHpr95EdVdF/+IQ4aVLq3axpBVQS2cyexMoKjB7UeFIlonRNUAycy9ccVZXwp1ShyqWrJJcOcEdtNOJHKIQohlCVmG0JDr1jDd/Yi2fGYTX/kxx5oSaFrPSLOz3Bcyxwb/B3C+5ZaGkYAiB+pcZxfRAF5cDpDrS5V0raqdfwO2+pNsam+p5V79M8hddGr6xUMM972izO9fCI3fAIhTK9FM/sDa9y+oTGu9bLBg6nrKOvZMEnKbmPMpGJ13o9c+qxhklzYfSG6X28R1hXG8Ct/WpmpZhPQbEK9+ggLZwHXDdomUeZ74USOgt5hhwOg+R+pJeWrgz3L5WX8yYyh9L40v1bo/7ioeqxhJOPKdju8Q30YEOZ6addlUyFl3F6Zisr6RsT0whGlUDoevvHvvShljJU/rcie1sUmikeI4DeBE7UnuDCEkeDCB+OgCW7IiMI0L48mryJe2T7eARGY88oZklDGIUBtREp8zKk8hcHBntKnTszMd0IioW4CkgcAuh9p8oNJ5on+dwmckr94=
  email: false