sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew build"
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then docker
  build --no-cache --pull -t quay.io/wisvch/feedback-tool:$TRAVIS_BUILD_NUMBER .;
  fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then docker
  login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io; docker push quay.io/wisvch/feedback-tool:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  email: false
  slack:
    rooms:
      secure: uCLBLnOEWsOHarQOZZTc3bXsV8vLvaZYMbXWfDFJgJ6+HPPa+XN+BbHdCyIosyGsxuON6qzFDkbiopc2mK98f3GtCKwOpgfc7y6oU0Gev621qDihnE4U+QGO88rl3Oi9Y8j6m8MbtTrA2rnywCl+mWM4wSRpIVTYscYeSibxjVe4Yznag+GaJLnPWgPK+wV/kS97wdaCygqhpW63y3hQdoT4O8nvuwQXIq/K3wqqpdGZGNMJgHQI0uI9hyAlKqzdg8ttb09wHXcImofr43tnsaAfOsxz3y4Vl1kLLyPWokCewV5idpVhyToHsRxvWJrkE4ym9g2Gav2ksQt6Jd2wHvFNhqRqlJQWmypTBp5rq81uoCyirlYT2nt57LUCXJd9gCZlKendaOS4Gxo7aBu8HYceIjwAucDIVsxIOksMjTlnEdqXG/fdEuPMsCYXJKFgvANynN6vln6fbKR16TBuwp+kZ2iBpqm6/TvVaCrkV3dir1yrzt4Car54LPzAWsR7NC49gNVxYceoYwkcFQo49FPiTrM1Jf6REkbVJcLz0xuCUmW+w7h/jupuFcba2LRJScc97U6IjoguBwuPlNAk2C2wFLtLMlqo7XeKdpdKHnFJtwRVd+ySwZpehUuDcJlK3SP9HzWebPsoEtmtpQjRHuxNClnQH8qqEgHoIorpMHk=
